/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetsSlugRouteImport } from './routes/sets.$slug'
import { Route as SellersSlugRouteImport } from './routes/sellers.$slug'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as CardsIdRouteImport } from './routes/cards.$id'

const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSlugRoute = SetsSlugRouteImport.update({
  id: '/sets/$slug',
  path: '/sets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSlugRoute = SellersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SellersRoute,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GamesRoute,
} as any)
const CardsIdRoute = CardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/games': typeof GamesRouteWithChildren
  '/search': typeof SearchRoute
  '/sellers': typeof SellersRouteWithChildren
  '/cards/$id': typeof CardsIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/sets/$slug': typeof SetsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/games': typeof GamesRouteWithChildren
  '/search': typeof SearchRoute
  '/sellers': typeof SellersRouteWithChildren
  '/cards/$id': typeof CardsIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/sets/$slug': typeof SetsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/games': typeof GamesRouteWithChildren
  '/search': typeof SearchRoute
  '/sellers': typeof SellersRouteWithChildren
  '/cards/$id': typeof CardsIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/sets/$slug': typeof SetsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/games'
    | '/search'
    | '/sellers'
    | '/cards/$id'
    | '/games/$slug'
    | '/sellers/$slug'
    | '/sets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/games'
    | '/search'
    | '/sellers'
    | '/cards/$id'
    | '/games/$slug'
    | '/sellers/$slug'
    | '/sets/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/games'
    | '/search'
    | '/sellers'
    | '/cards/$id'
    | '/games/$slug'
    | '/sellers/$slug'
    | '/sets/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  GamesRoute: typeof GamesRouteWithChildren
  SearchRoute: typeof SearchRoute
  SellersRoute: typeof SellersRouteWithChildren
  CardsIdRoute: typeof CardsIdRoute
  SetsSlugRoute: typeof SetsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$slug': {
      id: '/sets/$slug'
      path: '/sets/$slug'
      fullPath: '/sets/$slug'
      preLoaderRoute: typeof SetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$slug': {
      id: '/sellers/$slug'
      path: '/$slug'
      fullPath: '/sellers/$slug'
      preLoaderRoute: typeof SellersSlugRouteImport
      parentRoute: typeof SellersRoute
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof GamesRoute
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesSlugRoute: typeof GamesSlugRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesSlugRoute: GamesSlugRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface SellersRouteChildren {
  SellersSlugRoute: typeof SellersSlugRoute
}

const SellersRouteChildren: SellersRouteChildren = {
  SellersSlugRoute: SellersSlugRoute,
}

const SellersRouteWithChildren =
  SellersRoute._addFileChildren(SellersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  GamesRoute: GamesRouteWithChildren,
  SearchRoute: SearchRoute,
  SellersRoute: SellersRouteWithChildren,
  CardsIdRoute: CardsIdRoute,
  SetsSlugRoute: SetsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
