---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next
  labels:
    app.kubernetes.io/name: next
    app.kubernetes.io/instance: next
    icc.platformatic.dev/scaler-max: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: next
  template:
    metadata:
      labels:
        app.kubernetes.io/name: next
        app.kubernetes.io/instance: next
        platformatic.dev/monitor: prometheus
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: next
      containers:
        - name: demo-application
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          env:
            - name: DB_DELAY_MIN
              value: "1"
            - name: DB_DELAY_MAX
              value: "5"
            - name: DB_DELAY_ENABLED
              value: "true"
            - name: PLT_ICC_URL
              value: "http://icc.platformatic.svc.cluster.local"
            - name: PLT_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: app
              containerPort: 3042
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
              scheme: HTTP
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status
              port: metrics
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /ready
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 15
          resources:
            requests:
              memory: '2Gi'
              cpu: '1000m'
            limits:
              memory: '2Gi'
              cpu: '1000m'

---
apiVersion: v1
kind: Service
metadata:
  name: next
  labels:
    app.kubernetes.io/instance: next
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: next
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: app
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: next
  labels:
    app.kubernetes.io/instance: next
spec:
  selector:
    matchLabels:
      platformatic.dev/monitor: prometheus
  podMetricsEndpoints:
    - port: metrics
      interval: 5s
